[package]
name = "bench"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
hex.workspace = true

alloy.workspace = true
alloy-evm.workspace = true

ark-bn254.workspace = true
ark-bls12-381.workspace = true
ark-ff.workspace = true

sha3.workspace = true

hash_to_curve.workspace = true
utils.workspace = true

foundry-contracts = { path = "../out/bindings" }
reqwest = { version = "0.12.24", features = ["blocking"] }
serde_json.workspace = true
serde.workspace = true
