[package]
name = "bench"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
hex.workspace = true

sha3.workspace = true
digest.workspace = true

ark-bn254.workspace = true
ark-ec.workspace = true
ark-ff.workspace = true

utils.workspace = true
alloy = { version = "1.0.38", features = ["node-bindings", "full"] }

foundry-contracts = { path = "../out/bindings" }
tokio = { version = "1.47.1", features = ["rt-multi-thread"] }
alloy-evm = "0.21.2"
