generate:
	cargo run --bin bench

plot:
	uv run --script plot.py

fetch: fetch-quicknet fetch-evmnet

fetch-evmnet:
	cargo run --bin fetch-drand evmnet data/evmnet_1000_rounds.bin

fetch-quicknet:
	cargo run --bin fetch-drand quicknet data/quicknet_1000_rounds.bin

format:
	cargo fmt
	uv format
